/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface Bookmark
 */
export interface Bookmark {
  /**
   *
   * @type {number}
   * @memberof Bookmark
   */
  readonly id: number
  /**
   *
   * @type {string}
   * @memberof Bookmark
   */
  title: string
  /**
   *
   * @type {number}
   * @memberof Bookmark
   */
  readonly bookmarkingsCount: number
  /**
   *
   * @type {Date}
   * @memberof Bookmark
   */
  readonly createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof Bookmark
   */
  readonly updatedAt: Date
}

/**
 * Check if a given object implements the Bookmark interface.
 */
export function instanceOfBookmark(value: object): value is Bookmark {
  if (!("id" in value) || value["id"] === undefined) return false
  if (!("title" in value) || value["title"] === undefined) return false
  if (!("bookmarkingsCount" in value) || value["bookmarkingsCount"] === undefined) return false
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false
  return true
}

export function BookmarkFromJSON(json: any): Bookmark {
  return BookmarkFromJSONTyped(json, false)
}

export function BookmarkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bookmark {
  if (json == null) {
    return json
  }
  return {
    id: json["id"],
    title: json["title"],
    bookmarkingsCount: json["bookmarkings_count"],
    createdAt: new Date(json["created_at"]),
    updatedAt: new Date(json["updated_at"])
  }
}

export function BookmarkToJSON(json: any): Bookmark {
  return BookmarkToJSONTyped(json, false)
}

export function BookmarkToJSONTyped(
  value?: Omit<Bookmark, "id" | "bookmarkings_count" | "created_at" | "updated_at"> | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    title: value["title"]
  }
}
