/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface KakaoAuthResponse
 */
export interface KakaoAuthResponse {
  /**
   * JWT Access Token
   * @type {string}
   * @memberof KakaoAuthResponse
   */
  access: string
  /**
   * JWT Refresh Token
   * @type {string}
   * @memberof KakaoAuthResponse
   */
  refresh: string
}

/**
 * Check if a given object implements the KakaoAuthResponse interface.
 */
export function instanceOfKakaoAuthResponse(value: object): value is KakaoAuthResponse {
  if (!("access" in value) || value["access"] === undefined) return false
  if (!("refresh" in value) || value["refresh"] === undefined) return false
  return true
}

export function KakaoAuthResponseFromJSON(json: any): KakaoAuthResponse {
  return KakaoAuthResponseFromJSONTyped(json, false)
}

export function KakaoAuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KakaoAuthResponse {
  if (json == null) {
    return json
  }
  return {
    access: json["access"],
    refresh: json["refresh"]
  }
}

export function KakaoAuthResponseToJSON(json: any): KakaoAuthResponse {
  return KakaoAuthResponseToJSONTyped(json, false)
}

export function KakaoAuthResponseToJSONTyped(
  value?: KakaoAuthResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    access: value["access"],
    refresh: value["refresh"]
  }
}
