/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface Login
 */
export interface Login {
  /**
   *
   * @type {string}
   * @memberof Login
   */
  username?: string
  /**
   *
   * @type {string}
   * @memberof Login
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof Login
   */
  password: string
}

/**
 * Check if a given object implements the Login interface.
 */
export function instanceOfLogin(value: object): value is Login {
  if (!("password" in value) || value["password"] === undefined) return false
  return true
}

export function LoginFromJSON(json: any): Login {
  return LoginFromJSONTyped(json, false)
}

export function LoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): Login {
  if (json == null) {
    return json
  }
  return {
    username: json["username"] == null ? undefined : json["username"],
    email: json["email"] == null ? undefined : json["email"],
    password: json["password"]
  }
}

export function LoginToJSON(json: any): Login {
  return LoginToJSONTyped(json, false)
}

export function LoginToJSONTyped(value?: Login | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {
    username: value["username"],
    email: value["email"],
    password: value["password"]
  }
}
