/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface Thumbnail
 */
export interface Thumbnail {
  /**
   *
   * @type {string}
   * @memberof Thumbnail
   */
  readonly url: string
}

/**
 * Check if a given object implements the Thumbnail interface.
 */
export function instanceOfThumbnail(value: object): value is Thumbnail {
  if (!("url" in value) || value["url"] === undefined) return false
  return true
}

export function ThumbnailFromJSON(json: any): Thumbnail {
  return ThumbnailFromJSONTyped(json, false)
}

export function ThumbnailFromJSONTyped(json: any, ignoreDiscriminator: boolean): Thumbnail {
  if (json == null) {
    return json
  }
  return {
    url: json["url"]
  }
}

export function ThumbnailToJSON(json: any): Thumbnail {
  return ThumbnailToJSONTyped(json, false)
}

export function ThumbnailToJSONTyped(value?: Omit<Thumbnail, "url"> | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {}
}
