/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface Video
 */
export interface Video {
  /**
   *
   * @type {string}
   * @memberof Video
   */
  readonly url: string
}

/**
 * Check if a given object implements the Video interface.
 */
export function instanceOfVideo(value: object): value is Video {
  if (!("url" in value) || value["url"] === undefined) return false
  return true
}

export function VideoFromJSON(json: any): Video {
  return VideoFromJSONTyped(json, false)
}

export function VideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Video {
  if (json == null) {
    return json
  }
  return {
    url: json["url"]
  }
}

export function VideoToJSON(json: any): Video {
  return VideoToJSONTyped(json, false)
}

export function VideoToJSONTyped(value?: Omit<Video, "url"> | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value
  }

  return {}
}
