import Header from "@/components/Header"
import Toast from "@/components/Toast"
import { Pretendard } from "@/fonts"
import "@/styles/globals.css"
import "@/styles/reset.css"
import { cn } from "@/utils/cn"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={(cn(Pretendard.variable), "px-[16px] md:px-[28px] lg:px-[120px]")}>
        <Header />
        {children}
        <Toast />
      </body>
    </html>
  )
}
