import Toast from "@/components/Toast"
import { Pretendard } from "@/fonts"
import "@/styles/globals.css"
import "@/styles/reset.css"
import { cn } from "@/utils/cn"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn(Pretendard.variable)}>
        {children}
        <Toast />
      </body>
    </html>
  )
}
