/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface ApiV1BookmarkingsWithoutBookmarkCreateRequest
 */
export interface ApiV1BookmarkingsWithoutBookmarkCreateRequest {
  /**
   * 북마크를 추가할 밈 ID 목록
   * @type {Array<number>}
   * @memberof ApiV1BookmarkingsWithoutBookmarkCreateRequest
   */
  memeIds: Array<number>
  /**
   * 추가할 북마크 ID 목록
   * @type {Array<number>}
   * @memberof ApiV1BookmarkingsWithoutBookmarkCreateRequest
   */
  bookmarkIds: Array<number>
}

/**
 * Check if a given object implements the ApiV1BookmarkingsWithoutBookmarkCreateRequest interface.
 */
export function instanceOfApiV1BookmarkingsWithoutBookmarkCreateRequest(
  value: object
): value is ApiV1BookmarkingsWithoutBookmarkCreateRequest {
  if (!("memeIds" in value) || value["memeIds"] === undefined) return false
  if (!("bookmarkIds" in value) || value["bookmarkIds"] === undefined) return false
  return true
}

export function ApiV1BookmarkingsWithoutBookmarkCreateRequestFromJSON(
  json: any
): ApiV1BookmarkingsWithoutBookmarkCreateRequest {
  return ApiV1BookmarkingsWithoutBookmarkCreateRequestFromJSONTyped(json, false)
}

export function ApiV1BookmarkingsWithoutBookmarkCreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiV1BookmarkingsWithoutBookmarkCreateRequest {
  if (json == null) {
    return json
  }
  return {
    memeIds: json["meme_ids"],
    bookmarkIds: json["bookmark_ids"]
  }
}

export function ApiV1BookmarkingsWithoutBookmarkCreateRequestToJSON(
  json: any
): ApiV1BookmarkingsWithoutBookmarkCreateRequest {
  return ApiV1BookmarkingsWithoutBookmarkCreateRequestToJSONTyped(json, false)
}

export function ApiV1BookmarkingsWithoutBookmarkCreateRequestToJSONTyped(
  value?: ApiV1BookmarkingsWithoutBookmarkCreateRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    meme_ids: value["memeIds"],
    bookmark_ids: value["bookmarkIds"]
  }
}
