/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface ApiV1MemesBookmarkIdsRetrieve200Response
 */
export interface ApiV1MemesBookmarkIdsRetrieve200Response {
  /**
   * List of bookmark IDs for the specified meme.
   * @type {Array<number>}
   * @memberof ApiV1MemesBookmarkIdsRetrieve200Response
   */
  bookmarkIds?: Array<number>
}

/**
 * Check if a given object implements the ApiV1MemesBookmarkIdsRetrieve200Response interface.
 */
export function instanceOfApiV1MemesBookmarkIdsRetrieve200Response(
  value: object
): value is ApiV1MemesBookmarkIdsRetrieve200Response {
  return true
}

export function ApiV1MemesBookmarkIdsRetrieve200ResponseFromJSON(json: any): ApiV1MemesBookmarkIdsRetrieve200Response {
  return ApiV1MemesBookmarkIdsRetrieve200ResponseFromJSONTyped(json, false)
}

export function ApiV1MemesBookmarkIdsRetrieve200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiV1MemesBookmarkIdsRetrieve200Response {
  if (json == null) {
    return json
  }
  return {
    bookmarkIds: json["bookmark_ids"] == null ? undefined : json["bookmark_ids"]
  }
}

export function ApiV1MemesBookmarkIdsRetrieve200ResponseToJSON(json: any): ApiV1MemesBookmarkIdsRetrieve200Response {
  return ApiV1MemesBookmarkIdsRetrieve200ResponseToJSONTyped(json, false)
}

export function ApiV1MemesBookmarkIdsRetrieve200ResponseToJSONTyped(
  value?: ApiV1MemesBookmarkIdsRetrieve200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    bookmark_ids: value["bookmarkIds"]
  }
}
