/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { Bookmarking } from "./Bookmarking"
import { BookmarkingFromJSON, BookmarkingFromJSONTyped, BookmarkingToJSON, BookmarkingToJSONTyped } from "./Bookmarking"

/**
 *
 * @export
 * @interface PaginatedBookmarkingList
 */
export interface PaginatedBookmarkingList {
  /**
   *
   * @type {number}
   * @memberof PaginatedBookmarkingList
   */
  count: number
  /**
   *
   * @type {string}
   * @memberof PaginatedBookmarkingList
   */
  next?: string | null
  /**
   *
   * @type {string}
   * @memberof PaginatedBookmarkingList
   */
  previous?: string | null
  /**
   *
   * @type {Array<Bookmarking>}
   * @memberof PaginatedBookmarkingList
   */
  results: Array<Bookmarking>
}

/**
 * Check if a given object implements the PaginatedBookmarkingList interface.
 */
export function instanceOfPaginatedBookmarkingList(value: object): value is PaginatedBookmarkingList {
  if (!("count" in value) || value["count"] === undefined) return false
  if (!("results" in value) || value["results"] === undefined) return false
  return true
}

export function PaginatedBookmarkingListFromJSON(json: any): PaginatedBookmarkingList {
  return PaginatedBookmarkingListFromJSONTyped(json, false)
}

export function PaginatedBookmarkingListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginatedBookmarkingList {
  if (json == null) {
    return json
  }
  return {
    count: json["count"],
    next: json["next"] == null ? undefined : json["next"],
    previous: json["previous"] == null ? undefined : json["previous"],
    results: (json["results"] as Array<any>).map(BookmarkingFromJSON)
  }
}

export function PaginatedBookmarkingListToJSON(json: any): PaginatedBookmarkingList {
  return PaginatedBookmarkingListToJSONTyped(json, false)
}

export function PaginatedBookmarkingListToJSONTyped(
  value?: PaginatedBookmarkingList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    count: value["count"],
    next: value["next"],
    previous: value["previous"],
    results: (value["results"] as Array<any>).map(BookmarkingToJSON)
  }
}
