/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { Tag } from "./Tag"
import { TagFromJSON, TagFromJSONTyped, TagToJSON, TagToJSONTyped } from "./Tag"

/**
 *
 * @export
 * @interface PaginatedTagList
 */
export interface PaginatedTagList {
  /**
   *
   * @type {number}
   * @memberof PaginatedTagList
   */
  count: number
  /**
   *
   * @type {string}
   * @memberof PaginatedTagList
   */
  next?: string | null
  /**
   *
   * @type {string}
   * @memberof PaginatedTagList
   */
  previous?: string | null
  /**
   *
   * @type {Array<Tag>}
   * @memberof PaginatedTagList
   */
  results: Array<Tag>
}

/**
 * Check if a given object implements the PaginatedTagList interface.
 */
export function instanceOfPaginatedTagList(value: object): value is PaginatedTagList {
  if (!("count" in value) || value["count"] === undefined) return false
  if (!("results" in value) || value["results"] === undefined) return false
  return true
}

export function PaginatedTagListFromJSON(json: any): PaginatedTagList {
  return PaginatedTagListFromJSONTyped(json, false)
}

export function PaginatedTagListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTagList {
  if (json == null) {
    return json
  }
  return {
    count: json["count"],
    next: json["next"] == null ? undefined : json["next"],
    previous: json["previous"] == null ? undefined : json["previous"],
    results: (json["results"] as Array<any>).map(TagFromJSON)
  }
}

export function PaginatedTagListToJSON(json: any): PaginatedTagList {
  return PaginatedTagListToJSONTyped(json, false)
}

export function PaginatedTagListToJSONTyped(
  value?: PaginatedTagList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    count: value["count"],
    next: value["next"],
    previous: value["previous"],
    results: (value["results"] as Array<any>).map(TagToJSON)
  }
}
