/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { Memo } from "./Memo"
import { MemoFromJSON, MemoFromJSONTyped, MemoToJSON, MemoToJSONTyped } from "./Memo"

/**
 *
 * @export
 * @interface PaginatedMemoList
 */
export interface PaginatedMemoList {
  /**
   *
   * @type {number}
   * @memberof PaginatedMemoList
   */
  count: number
  /**
   *
   * @type {string}
   * @memberof PaginatedMemoList
   */
  next?: string | null
  /**
   *
   * @type {string}
   * @memberof PaginatedMemoList
   */
  previous?: string | null
  /**
   *
   * @type {Array<Memo>}
   * @memberof PaginatedMemoList
   */
  results: Array<Memo>
}

/**
 * Check if a given object implements the PaginatedMemoList interface.
 */
export function instanceOfPaginatedMemoList(value: object): value is PaginatedMemoList {
  if (!("count" in value) || value["count"] === undefined) return false
  if (!("results" in value) || value["results"] === undefined) return false
  return true
}

export function PaginatedMemoListFromJSON(json: any): PaginatedMemoList {
  return PaginatedMemoListFromJSONTyped(json, false)
}

export function PaginatedMemoListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedMemoList {
  if (json == null) {
    return json
  }
  return {
    count: json["count"],
    next: json["next"] == null ? undefined : json["next"],
    previous: json["previous"] == null ? undefined : json["previous"],
    results: (json["results"] as Array<any>).map(MemoFromJSON)
  }
}

export function PaginatedMemoListToJSON(json: any): PaginatedMemoList {
  return PaginatedMemoListToJSONTyped(json, false)
}

export function PaginatedMemoListToJSONTyped(
  value?: PaginatedMemoList | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    count: value["count"],
    next: value["next"],
    previous: value["previous"],
    results: (value["results"] as Array<any>).map(MemoToJSON)
  }
}
