/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 *
 * @export
 * @interface PatchedMemo
 */
export interface PatchedMemo {
  /**
   *
   * @type {number}
   * @memberof PatchedMemo
   */
  readonly id?: number
  /**
   *
   * @type {number}
   * @memberof PatchedMemo
   */
  meme?: number
  /**
   *
   * @type {string}
   * @memberof PatchedMemo
   */
  content?: string
  /**
   *
   * @type {Date}
   * @memberof PatchedMemo
   */
  readonly createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof PatchedMemo
   */
  readonly updatedAt?: Date
}

/**
 * Check if a given object implements the PatchedMemo interface.
 */
export function instanceOfPatchedMemo(value: object): value is PatchedMemo {
  return true
}

export function PatchedMemoFromJSON(json: any): PatchedMemo {
  return PatchedMemoFromJSONTyped(json, false)
}

export function PatchedMemoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedMemo {
  if (json == null) {
    return json
  }
  return {
    id: json["id"] == null ? undefined : json["id"],
    meme: json["meme"] == null ? undefined : json["meme"],
    content: json["content"] == null ? undefined : json["content"],
    createdAt: json["created_at"] == null ? undefined : new Date(json["created_at"]),
    updatedAt: json["updated_at"] == null ? undefined : new Date(json["updated_at"])
  }
}

export function PatchedMemoToJSON(json: any): PatchedMemo {
  return PatchedMemoToJSONTyped(json, false)
}

export function PatchedMemoToJSONTyped(
  value?: Omit<PatchedMemo, "id" | "created_at" | "updated_at"> | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    meme: value["meme"],
    content: value["content"]
  }
}
