/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 * 사용자가 연결한 소셜 계정을 반환하는 Serializer
 * @export
 * @interface SocialAccount
 */
export interface SocialAccount {
  /**
   *
   * @type {string}
   * @memberof SocialAccount
   */
  readonly provider: string
  /**
   *
   * @type {string}
   * @memberof SocialAccount
   */
  readonly uid: string
}

/**
 * Check if a given object implements the SocialAccount interface.
 */
export function instanceOfSocialAccount(value: object): value is SocialAccount {
  if (!("provider" in value) || value["provider"] === undefined) return false
  if (!("uid" in value) || value["uid"] === undefined) return false
  return true
}

export function SocialAccountFromJSON(json: any): SocialAccount {
  return SocialAccountFromJSONTyped(json, false)
}

export function SocialAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialAccount {
  if (json == null) {
    return json
  }
  return {
    provider: json["provider"],
    uid: json["uid"]
  }
}

export function SocialAccountToJSON(json: any): SocialAccount {
  return SocialAccountToJSONTyped(json, false)
}

export function SocialAccountToJSONTyped(
  value?: Omit<SocialAccount, "provider" | "uid"> | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {}
}
