/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
import type { TagCategory } from "./TagCategory"
import { TagCategoryFromJSON, TagCategoryFromJSONTyped, TagCategoryToJSON, TagCategoryToJSONTyped } from "./TagCategory"

/**
 *
 * @export
 * @interface Tag
 */
export interface Tag {
  /**
   *
   * @type {number}
   * @memberof Tag
   */
  readonly id: number
  /**
   *
   * @type {string}
   * @memberof Tag
   */
  name: string
  /**
   *
   * @type {TagCategory}
   * @memberof Tag
   */
  category: TagCategory
  /**
   *
   * @type {number}
   * @memberof Tag
   */
  readonly popularity: number
  /**
   *
   * @type {number}
   * @memberof Tag
   */
  readonly memesCount: number
  /**
   *
   * @type {number}
   * @memberof Tag
   */
  readonly bookmarkingsCount: number
}

/**
 * Check if a given object implements the Tag interface.
 */
export function instanceOfTag(value: object): value is Tag {
  if (!("id" in value) || value["id"] === undefined) return false
  if (!("name" in value) || value["name"] === undefined) return false
  if (!("category" in value) || value["category"] === undefined) return false
  if (!("popularity" in value) || value["popularity"] === undefined) return false
  if (!("memesCount" in value) || value["memesCount"] === undefined) return false
  if (!("bookmarkingsCount" in value) || value["bookmarkingsCount"] === undefined) return false
  return true
}

export function TagFromJSON(json: any): Tag {
  return TagFromJSONTyped(json, false)
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
  if (json == null) {
    return json
  }
  return {
    id: json["id"],
    name: json["name"],
    category: TagCategoryFromJSON(json["category"]),
    popularity: json["popularity"],
    memesCount: json["memes_count"],
    bookmarkingsCount: json["bookmarkings_count"]
  }
}

export function TagToJSON(json: any): Tag {
  return TagToJSONTyped(json, false)
}

export function TagToJSONTyped(
  value?: Omit<Tag, "id" | "popularity" | "memes_count" | "bookmarkings_count"> | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {
    name: value["name"],
    category: TagCategoryToJSON(value["category"])
  }
}
