/* tslint:disable */
/* eslint-disable */
/**
 * Dionysus API
 * Meme Project
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dev.shinkeonkim@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime"
/**
 * User model w/o password
 * @export
 * @interface UserDetails
 */
export interface UserDetails {
  /**
   *
   * @type {number}
   * @memberof UserDetails
   */
  readonly pk: number
  /**
   *
   * @type {string}
   * @memberof UserDetails
   */
  readonly email: string
}

/**
 * Check if a given object implements the UserDetails interface.
 */
export function instanceOfUserDetails(value: object): value is UserDetails {
  if (!("pk" in value) || value["pk"] === undefined) return false
  if (!("email" in value) || value["email"] === undefined) return false
  return true
}

export function UserDetailsFromJSON(json: any): UserDetails {
  return UserDetailsFromJSONTyped(json, false)
}

export function UserDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDetails {
  if (json == null) {
    return json
  }
  return {
    pk: json["pk"],
    email: json["email"]
  }
}

export function UserDetailsToJSON(json: any): UserDetails {
  return UserDetailsToJSONTyped(json, false)
}

export function UserDetailsToJSONTyped(
  value?: Omit<UserDetails, "pk" | "email"> | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value
  }

  return {}
}
