name: git push into another repo to deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
        with:
          source-directory: "output"
          destination-github-username: memez-party
          destination-repository-name: meme-party-front-deploy
          user-email: ${{ secrets.DEPLOY_EMAIL }}
          # commit-message: "${{ github.event.commits[0].message || 'Manual commit from GitHub Actions' }}"
          commit-message: "Deploy from Github Actions"
          target-branch: main

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
